// Code generated by "stringer -type=TerrainType"; DO NOT EDIT.

package world

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Grass-0]
	_ = x[Water-1]
	_ = x[DeepWater-2]
	_ = x[Desert-3]
	_ = x[Forest-4]
	_ = x[DeepForest-5]
	_ = x[Mountain-6]
	_ = x[HighMountain-7]
	_ = x[Snow-8]
	_ = x[Ice-9]
}

const _TerrainType_name = "GrassWaterDeepWaterDesertForestDeepForestMountainHighMountainSnowIce"

var _TerrainType_index = [...]uint8{0, 5, 10, 19, 25, 31, 41, 49, 61, 65, 68}

func (i TerrainType) String() string {
	if i < 0 || i >= TerrainType(len(_TerrainType_index)-1) {
		return "TerrainType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TerrainType_name[_TerrainType_index[i]:_TerrainType_index[i+1]]
}
