[package]
name = "ptwar-server"
version = "0.1.0"
edition = "2021"

[dependencies]
ptwar = { path = "../ptwar" }
env_logger = "0.11.6"
tokio = { version = "1", features = ["full"] }
log = "0.4.25"
async-trait = "0.1.86"